const courses =[
    {
        altCard: false,
        category: 'Course',
        title: "Heal Your Trauma",
        backgroundImage: '/images/trauma.jpeg',
        card_description: 'Learn the skills to heal yourself from past trauma.',
        description: 'The goal of this course is to teach you the skills you will need so that you have a great understanding of what trauma is.<br />You will learn how to heal yourself from it and apply the skills you have gained confidently so that you will be able to handle any situation life may throw at you.',
        url: "heal-your-trauma",
        courseList: [
            'Intro - What Is Trauma?',
            'Awareness - The Conscious and Subconscious',
            'Feelings & Thoughts - What are they?',
            'Our Core Wounds - Childhood Trauma',
            'Relationships and Codependency',
            'Our Beliefs - How to change a belief?',
            'Shadow Work - What is it and how to do it?',
            'Parts Work - What is it and how to do it?',
            'The Nervous System',
            'Self love - How to practise self love?',
            'How to let go - Becoming the new you (Meditation)',
            'Activate your heart - Becoming the love that you naturally are (Meditation)',
            'Healing your inner child (Meditation)',
        ],
        comingSoon: true,
        comingSoonDate: 'April 2022',
    },
    {
        altCard: false,
        category: 'Meditation',
        title: "How To Let Go - Becoming A New You",
        backgroundImage: '/images/new-you.jpeg',
        card_description: 'Rewire your mind and body to become a new you.',
        description: 'The goal of this meditation is to get you out of the habit of thoughts that feed the body\'s addiction to stress. From there, you will be able to align yourself with more desirable thoughts which will take you towards your desired destiny in life',
        url: "How-to-let-go-becoming-a-new-you",
        courseList: [
            'In this meditation session I will guide you into being pure consciousness. <br /><br/> We will get to a stage of releasing all parts of the vehicle that your consciousness is driving that we call the "body". <br /><br/> At the moment of being pure consciousness I will teach you how to align with new thoughts and feel your desired emotions, such as love or abundance. You will literally reprogramme your mind and body to go towards your desired destiny in life, becoming the new you. <br /><br/> Our worrying thoughts turn on the stress hormones in our body. These stress hormones are addictive to us which in turn feed us more worrying thoughts. This is the body\'s way of getting the chemicals of stress that it has become addicted to. Yes, we are addicted to our worrying thoughts. <br /><br/> The way we stop this is learning how to observe our thoughts so that we can choose which thoughts to align with. <br /><br/> By being able to experience this you will learn that you are separate from your thoughts and feelings. You will be able to get an understanding that at any point of the day you have the ability to separate yourself from your mind, body, thoughts and feelings. <br /><br/> This is not only very beneficial for your mental health but it is very healing as well. This skill can be used in the moments that our emotions get the best of us and we can also use it to improve the relationships that we have in our lives.',
        ],
        comingSoon: true,
        comingSoonDate: 'April 2022',
    },
    {
        altCard: true,
    },
];
export default courses;
