export const globalMailingList = [
    "ariansamouie@gmail.com",
    "ariansamouiecoach@outlook.com",
    // "ashley_collins87@hotmail.co.uk",
    // "e.a.ungan@gmail.com",
    // "paulahalliday07@icloud.com",
    // "ausrytea5@yahoo.co.uk",
    // "sarah2682e@icloud.com",
    // "cazziembm@gmail.com",
    // "jj01.joseph@gmail.com",
    // "nadz81@hotmail.co.uk",
    // "daniella_m_terry@hotmail.com",
    // "donna-crichton@outlook.com",
    // "cjbates75@icloud.com",
    // "lerhyshendy@icloud.com",
    // "angel_a68@hotmail.co.uk",
    // "y.walters66@outlook.com",
    // "tabafard@yahoo.co.uk",
    // "ajpage7829@hotmail.com",
    // "s_sal@hotmail.co.uk",
    // "gary@spiritedstrength.com",
    // "raffaellaluoni@gmail.com",
]